### ISSUE TITLE
OSError: CompVis/stable-diffusion-v1-4 does not appear to have a file named diffusion_pytorch_model.bin.

### ISSUE THREAD

**Issue by fundwotsai2001** [csyxwei/ELITE#11]
After doing all the steps above, when I run "bash inference_local.sh", I got this error, OSError: CompVis/stable-diffusion-v1-4 does not appear to have a file named diffusion_pytorch_model.bin. How can I solve this? Thank you in advance!

**Comment by csyxwei** [comment]
Hi, 

you can change [Line 47](https://github.com/csyxwei/ELITE/blob/84b6f2f43957e883ab7a40cf2c3e4519d854a25a/inference_local.py#L47) in inference_local.py from

```python
local_path_only = diffusion_model_path is not None
```

to 

```python
local_path_only = False
```
