### ISSUE TITLE
custom dataset without mask

### ISSUE THREAD

**Issue by baiyang4** [csyxwei/ELITE#12]
Hi, can I use your model on a custom dataset. If so, how to adjest the code.
Thanks a lot!

**Comment by csyxwei** [comment]
Hi, you can firstly extract the object mask with [image-matting-app](https://huggingface.co/spaces/vivym/image-matting-app) (mode: Generate Mask), or other segmentation methods (e.g., [SAM](https://github.com/facebookresearch/segment-anything)). And then using the extracted masks for inference.
