### ISSUE TITLE
Is a Global Mapper necessary?

### ISSUE THREAD

**Issue by sam-motamed** [csyxwei/ELITE#13]
Not an issue but a question. This might be a silly question, but why train a Global Mapping network to get  embeddings. Why not use the pre-trained CLIP's layer outputs directly as these embeddings?

**Comment by csyxwei** [comment]
Hi,

Following [Textual Inversion](https://arxiv.org/abs/2208.01618), we utilize textual word embedding to represent the new concept. However, as the output of the CLIP Image Encoder is not inherently aligned with the textual word embedding space (only the output spaces of the CLIP image encoder and text encoder are aligned), we employ a global mapping to perform the necessary mapping.

[InstantBooth](https://arxiv.org/abs/2304.03411) leverages the textual feature embedding (i.e., the penultimate layer output of the text encoder) to represent the new concept. Nonetheless, it still requires an additional mapper to map the image feature as the textual feature.

**Comment by sam-motamed** [comment]
thanks
