### ISSUE TITLE
Why is the value range of the mask 0-255 instead of 0-1 when calculating  local training?

### ISSUE THREAD

**Issue by 333caowei** [csyxwei/ELITE#17]
Why is the value range of the mask 0-255 instead of 0-1 when calculating inj_embedding_local * mask during local training? inj_embedding_local is the patch img emb obtained after CLIP extraction. When inj_embedding_local * mask is performed, I think the mask should be in the range of 0-1 instead of 0-255?
<img width="884" alt="image" src="https://github.com/csyxwei/ELITE/assets/4569055/4608381c-2f41-4fd8-8d92-5833e89db8ba">

**Comment by csyxwei** [comment]
Hi, the value of the mask during training is 0-1; we have normalized the value of the mask into [0, 1] in [datasets.py](https://github.com/csyxwei/ELITE/blob/84b6f2f43957e883ab7a40cf2c3e4519d854a25a/datasets.py#L527).

**Comment by 333caowei** [comment]
> Hi, the value of the mask during training is 0-1; we have normalized the value of the mask into [0, 1] in [datasets.py](https://github.com/csyxwei/ELITE/blob/84b6f2f43957e883ab7a40cf2c3e4519d854a25a/datasets.py#L527).

But the param normalize of  get_tensor_clip  set False  
<img width="1209" alt="image" src="https://github.com/csyxwei/ELITE/assets/4569055/b88f9648-fa4f-4238-a74f-47e98b623ba9">

**Comment by csyxwei** [comment]
`transforms.ToTensor()` will scale the tensor from [0, 255] to [0, 1].
![image](https://github.com/csyxwei/ELITE/assets/23421814/755ad5a0-3d6a-4b77-b489-d151e2fb76d3)

**Comment by 333caowei** [comment]
got it, thank you so much
