### ISSUE TITLE
about device

### ISSUE THREAD

**Issue by LoneChristmas** [csyxwei/ELITE#18]
I use 4 4090GPUs, each has 24GB memory, but I get "out of memory"，could you tell me about something about your device.

**Comment by csyxwei** [comment]
Hi, we use 4 x V100 32G to train our model. You can use a small batch size to reduce memory requirements.

**Comment by LoneChristmas** [comment]
Hi, thanks for the last reply. This time I want to know about the following code in your local mapping network: ` hidden_state = getattr(self, f'mapping_{i}')(emb[:, :1]) + getattr(self, f'mapping_patch_{i}')(emb[:, 1:]) ` . Seems like you broadcast the cls_token which that comes from Vision Transformer in CLIP image encoder to the rest tokens which represent features from 14*14 patchs. Could you tell me why did you do that? And I also want to know what are the differences between the features from CNN's and from ViTs.

**Comment by LoneChristmas** [comment]
And I have also noticed that in your paper, you listed a form about CLIP scores(CLIP-I and CLIP-T). About CLIP-T, noticing that there is a placeholder token 'S' which is not meaningful for text inputs when calculating CLIP-T. How do you do ?

**Comment by csyxwei** [comment]
> Hi, thanks for the last reply. This time I want to know about the following code in your local mapping network: `hidden_state = getattr(self, f'mapping_{i}')(emb[:, :1]) + getattr(self, f'mapping_patch_{i}')(emb[:, 1:])` . Seems like you broadcast the cls_token which that comes from Vision Transformer in CLIP image encoder to the rest tokens which represent features from 14*14 patchs. Could you tell me why did you do that? And I also want to know what are the differences between the features from CNN's and from ViTs.

Hi, we only trained our method using the ViT-based CLIP model, and I think there wouldn't be a significant difference between training the model with features from CNNs and those from ViTs. Additionally, given that the CLS token captures the semantics of the entire image, we processed it separately, and integrated it with the features from other patches for a more robust representation.

**Comment by csyxwei** [comment]
> And I have also noticed that in your paper, you listed a form about CLIP scores(CLIP-I and CLIP-T). About CLIP-T, noticing that there is a placeholder token 'S' which is not meaningful for text inputs when calculating CLIP-T. How do you do ?

When calculating the CLIP-T, we will replace 'S' with the image category to extract text features, such as dog, cat, etc.

**Comment by LoneChristmas** [comment]
Thanks for your reply, and I also want to know how to judge if the local mapping network converges?  Because I cannot afford traning your model for nearly a week. But I cannot see the `loss_mle + loss_reg` converges.  And the term `loss_reg` seems getting higher and higher. And here's my parameters for training the local mapping networks:
`export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export DATA_DIR='./datasets/Open_Images/'
CUDA_VISIBLE_DEVICES=0 accelerate launch --config_file 1_gpu.json --main_process_port 25658 train_local.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$DATA_DIR \
  --placeholder_token="S" \
  --resolution=512 \
  --train_batch_size=2 \
  --gradient_accumulation_steps=1 \
  --max_train_steps=20000 \
  --learning_rate=1e-5 --scale_lr \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --global_mapper_path "./checkpoints/global_mapper.pt" \
  --output_dir="./elite_experiment1/local_mapping_200_new" \
  --save_steps 2000`.

**Comment by LoneChristmas** [comment]
![image](https://github.com/csyxwei/ELITE/assets/108116094/f671d58b-c088-4f09-92b8-7a41d6e72349)
sorry for the bad format.

**Comment by csyxwei** [comment]
In our experiments, the loss does not converge either. Therefore, we use the visualization results during training to monitor the training process.

**Comment by LoneChristmas** [comment]
Thanks for providing the information; it has given me a clearer understanding of the model.
