### ISSUE TITLE
(SOLVED)hugginface demo is a fail

### ISSUE THREAD

**Issue by 2blackbar** [csyxwei/ELITE#2]
You guys even tested it ?

**Comment by csyxwei** [comment]
Hi, we have tested the demo.

![image](https://user-images.githubusercontent.com/23421814/224873479-c4cf44d6-8c99-4ef9-b972-87c25fe923ee.png)

**Comment by Minniemu** [comment]
@csyxwei It seems like the link on the README is fail, hope to see your complete demo link, thanks!

**Comment by csyxwei** [comment]
Hi, the demo link is https://huggingface.co/spaces/ELITE-library/ELITE. I have just tried it, and it works well. Could you give some more information.

**Comment by Minniemu** [comment]
Hi, I can see the demo now, thanks for your help, and look forward for your amazing work.

**Comment by 2blackbar** [comment]
Now it works well
![rtyhrtrt](https://user-images.githubusercontent.com/33694664/225186254-dc2e7af2-fcf2-42cd-9be9-5dd2a11f34ad.png)

**Comment by ming1993li** [comment]
Sorry, I have tried the online demo website many times. But it always gives an error. Do you know the reason?

**Comment by csyxwei** [comment]
@ming1993li We have restarted it, you can try it again.

**Comment by ming1993li** [comment]
Thank you
