### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by idonahum** [csyxwei/ELITE#20]
Hi, Thanks for the great work!

Did you use a single prompt "A photo of S*" for all samples during training? or did you varied it with different prompts? 

Thanks!

**Comment by csyxwei** [comment]
Hi,

We randomly sampled a prompt from a small set of templates; you can check our code in [dataset.py](https://github.com/csyxwei/ELITE/blob/84b6f2f43957e883ab7a40cf2c3e4519d854a25a/datasets.py#L17) for more details.

**Comment by idonahum** [comment]
Thanks for the fast response!

I see that the small set of templates doesnt include some of the prompts presented in the paper results, for example prompts presented in Figure 10, are you saying these small small subset was enough to generalize all other prompts? 

Thanks!

**Comment by csyxwei** [comment]
We only used prompts like "a photo of S*" to train the model, and found it can generalize to other prompts. Also, it would be better to utilize matching text for each image if such paired data is available.

**Comment by idonahum** [comment]
Thank you! 

If I can ask another question:
on 
https://github.com/csyxwei/ELITE/blob/84b6f2f43957e883ab7a40cf2c3e4519d854a25a/datasets.py#L266

Why is placeholder_idx = idx + 1 and not just idx? Isnt the +1 will override existing token? for example "{} latte art" , place holder idx will be 1, which will override latte.

Thanks.

**Comment by csyxwei** [comment]
A `SOT` token (start of text) will be added at the beginning after tokenization, so the index will be idx + 1. And also, the `latte` will not be overided.

**Comment by idonahum** [comment]
Thanks!
