### ISSUE TITLE
运行结果出错

### ISSUE THREAD

**Issue by liyuqiao-888** [csyxwei/ELITE#21]
学长好，我在运行bash inference_local.sh的时候，产生的图片是这样的，请问您有遇到过这种情况吗？我不知道该怎么解决了。
![00000_00042](https://github.com/user-attachments/assets/618ed6fd-eea7-4b2b-8dc9-04d9f76c12ce)

**Comment by csyxwei** [comment]
你好~ 可以先检查一下安装的库的版本是否和requirements.txt里一致，尤其是diffusers的版本

**Comment by liyuqiao-888** [comment]
> 你好~ 可以先检查一下安装的库的版本是否和requirements.txt里一致，尤其是diffusers的版本

谢谢学长，以解决

**Comment by liyuqiao-888** [comment]
> 你好~ 可以先检查一下安装的库的版本是否和requirements.txt里一致，尤其是diffusers的版本

谢谢学长，已解决
