### ISSUE TITLE
if the "concept" is a face of one person , the  generation is bad, and don't like the input person.  How to solve it? thanks

### ISSUE THREAD

**Issue by wangzhaolei** [csyxwei/ELITE#3]

**Comment by csyxwei** [comment]
Hi, you can try to finetune the pretrained model on some face datasets, such as FFHQ or CelebA.  Our model is trained on the test dataset of OpenImages; introducing more face images may help improve the model's ability to handle faces.

**Comment by wangzhaolei** [comment]
> Hi, you can try to finetune the pretrained model on some face datasets, such as FFHQ or CelebA. Our model is trained on the test dataset of OpenImages; introducing more face images may help improve the model's ability to handle faces.

I will try，thankyou！
