### ISSUE TITLE
about global average pooling

### ISSUE THREAD

**Issue by wty-ustc** [csyxwei/ELITE#5]
Thanks for your great work! In your 3.2 section of your paper, you said "Global average pooling is employed to obtain the final word embedding." I want to make sure that the 'mean’ operation in the following code corresponds to global average pooling. Right?
https://github.com/csyxwei/ELITE/blob/665fa85d22c72781a593f7872a5af2122ddcc202/train_global.py#L65

**Comment by csyxwei** [comment]
Hi, you are right.

**Comment by wty-ustc** [comment]
thx!



---Original---
From: "Yuxiang ***@***.***&gt;
Date: Fri, Mar 17, 2023 11:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [csyxwei/ELITE] about global average pooling (Issue #5)




 
Hi, you are right.
