### ISSUE TITLE
Questions about the proposed method

### ISSUE THREAD

**Issue by hello451** [csyxwei/ELITE#7]
If I understand correctly, ELITE needs additionaly mask input compared to the related work, right? Although it has quicker editting, it seemed that ELITE should be compared to the baselines that also using mask. It is actually unfair to compare it with Textual Inversion, Dreambooth...
And then here comes another question: Now we have the mask, we do not directly use mask into the "global network training stage"?

**Comment by csyxwei** [comment]
We have tried to use masks directly in the "global network training stage", and it does improve the editability, but less than the current way. We will explore better ways to leverage the mask to learn a well-editable word embedding.
